### ISSUE TITLE
Prevent Error talking to autoupdate as Deli if not allowed to seeLoS

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-autoupdate-service#870]
**Current behaviour:**
If a participant is allowed to put themselves on the LoS but not allowed to see the LoS then opening some pages produces an "Error talking to autoupdate service"

**Reproduction:**
1. Participant A group settings for A:
2. A needs the right to put themselves on the LoS
3. A is not allowed to see the LoS
4. A is allowed to see the agenda and the front page
5. Login as A
6.  in a meeting: navigate to the start page
7. reload the page
8. navigate to the agenda
9. error talking to autoupdate occurs

**Logs from the autoupdate:**
```
autoupdate_1        | 2024/03/01 12:10:15 http: panic serving 172.22.0.14:42328: runtime error: invalid memory address or nil pointer dereference
autoupdate_1        | goroutine 2939 [running]:
autoupdate_1        | net/http.(*conn).serve.func1()
autoupdate_1        |   /usr/local/go/src/net/http/server.go:1898 +0xbe
autoupdate_1        | panic({0xabfe40?, 0x1146080?})
autoupdate_1        |   /usr/local/go/src/runtime/panic.go:770 +0x132
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/pkg/datastore/dsfetch.(*ValueInt).Lazy(...)
autoupdate_1        |   /root/pkg/datastore/dsfetch/fields_generated.go:195
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.Speaker.see.func1(0x2, {0xc00052a880, 0xa, 0x10})
autoupdate_1        |   /root/internal/restrict/collection/speaker.go:73 +0x533
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.eachMeeting({0xc96d70, 0xc0000ad860}, 0xc0007c26f0, {0xc95b00, 0x11c8e20}, {0xc00054e780, 0xa, 0xc000101008?}, 0xc0000febc8)
autoupdate_1        |   /root/internal/restrict/collection/collection.go:260 +0x3cf
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.Speaker.see({}, {0xc96d70?, 0xc0000ad860?}, 0xc0000fec28?, {0xc00054e780?, 0xa89220?, 0xc0000fec01?})
autoupdate_1        |   /root/internal/restrict/collection/speaker.go:43 +0x6b
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.(*restrictCache).Modes.func1({0xc96d70, 0xc0000ad860}, 0xc0007c26f0, {0xc00054e6e0, 0xa, 0x1?})
autoupdate_1        |   /root/internal/restrict/collection/collection.go:120 +0x2d3
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict.restrict({0xc96d70, 0xc0000ad860}, {0xc8f360, 0xc0007c2300}, 0x2, 0xc0002c8900)
autoupdate_1        |   /root/internal/restrict/restrict.go:126 +0x791
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict.restricter.Get({{0xc8f360?, 0xc0007c2300?}, 0x40?}, {0xc96d70, 0xc0000ad860}, {0xc004f4aa80?, 0x1?, 0xc00054d220?})
autoupdate_1        |   /root/internal/restrict/restrict.go:57 +0xfd
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/keysbuilder.(*Builder).Update(0xc0003261c0, {0xc96d70, 0xc0000ad860}, {0xc8f5c0, 0xc0007c2348})
autoupdate_1        |   /root/internal/keysbuilder/keysbuilder.go:125 +0x3c3
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/autoupdate.(*connection).updatedData(0xc0001360e0, {0xc96d70, 0xc0000accc0})
autoupdate_1        |   /root/internal/autoupdate/connection.go:110 +0x1ca
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/autoupdate.(*connection).Next-fm.(*connection).Next.func1({0xc96d70, 0xc0000accc0})
autoupdate_1        |   /root/internal/autoupdate/connection.go:58 +0x6e
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.sendMessages({0xc96d70, 0xc0000accc0}, {0xc8f000, 0xc000136000}, 0x10?, {0xc8f520?, 0xc0003261c0?}, {0xc93210?, 0xc00011e4e0?}, 0x1)
autoupdate_1        |   /root/internal/http/http.go:331 +0xe2
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.autoupdateHandler.func1({0xc950e0, 0xc000136000}, 0xc000125200)
autoupdate_1        |   /root/internal/http/http.go:181 +0x959
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0x7f3b6ae2e4a8?, {0xc950e0?, 0xc000136000?}, 0x120?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.connectionCountMiddleware.func2({0xc950e0, 0xc000136000}, 0xc000125200)
autoupdate_1        |   /root/internal/http/http.go:485 +0x105
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0xc000124120?, {0xc950e0?, 0xc000136000?}, 0xc000124120?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.authMiddleware.func3({0xc950e0, 0xc000136000}, 0xc000124120)
autoupdate_1        |   /root/internal/http/http.go:373 +0xce
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0xc000124120?, {0xc950e0?, 0xc000136000?}, 0x0?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.validRequest.func4({0xc950e0?, 0xc000136000?}, 0x6e65ed?)
autoupdate_1        |   /root/internal/http/http.go:467 +0x6f
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0xc000120410?, {0xc950e0?, 0xc000136000?}, 0x10?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | net/http.(*ServeMux).ServeHTTP(0x411fa5?, {0xc950e0, 0xc000136000}, 0xc000124120)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2683 +0x1ad
autoupdate_1        | net/http.serverHandler.ServeHTTP({0xc929a0?}, {0xc950e0?, 0xc000136000?}, 0x6?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:3137 +0x8e
autoupdate_1        | net/http.(*conn).serve(0xc00032c090, {0xc96d70, 0xc00011ec90})
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2039 +0x5e8
autoupdate_1        | created by net/http.(*Server).Serve in goroutine 1
autoupdate_1        |   /usr/local/go/src/net/http/server.go:3285 +0x4b4
autoupdate_1        | 2024/03/01 12:10:16 http: panic serving 172.22.0.14:42338: runtime error: invalid memory address or nil pointer dereference
autoupdate_1        | goroutine 2942 [running]:
autoupdate_1        | net/http.(*conn).serve.func1()
autoupdate_1        |   /usr/local/go/src/net/http/server.go:1898 +0xbe
autoupdate_1        | panic({0xabfe40?, 0x1146080?})
autoupdate_1        |   /usr/local/go/src/runtime/panic.go:770 +0x132
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/pkg/datastore/dsfetch.(*ValueInt).Lazy(...)
autoupdate_1        |   /root/pkg/datastore/dsfetch/fields_generated.go:195
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.Speaker.see.func1(0x2, {0xc00019b300, 0xa, 0x10})
autoupdate_1        |   /root/internal/restrict/collection/speaker.go:73 +0x533
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.eachMeeting({0xc96d70, 0xc001e4d020}, 0xc00039ca50, {0xc95b00, 0x11c8e20}, {0xc0000de7d0, 0xa, 0xc000101008?}, 0xc0000febc8)
autoupdate_1        |   /root/internal/restrict/collection/collection.go:260 +0x3cf
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.Speaker.see({}, {0xc96d70?, 0xc001e4d020?}, 0xc0000fec28?, {0xc0000de7d0?, 0xa89220?, 0xc0000fec01?})
autoupdate_1        |   /root/internal/restrict/collection/speaker.go:43 +0x6b
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.(*restrictCache).Modes.func1({0xc96d70, 0xc001e4d020}, 0xc00039ca50, {0xc0000de780, 0xa, 0x1?})
autoupdate_1        |   /root/internal/restrict/collection/collection.go:120 +0x2d3
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict.restrict({0xc96d70, 0xc001e4d020}, {0xc8f360, 0xc00039c588}, 0x2, 0xc001e4dbf0)
autoupdate_1        |   /root/internal/restrict/restrict.go:126 +0x791
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict.restricter.Get({{0xc8f360?, 0xc00039c588?}, 0x40?}, {0xc96d70, 0xc001e4d020}, {0xc00137abb0?, 0x1?, 0xc0006210b0?})
autoupdate_1        |   /root/internal/restrict/restrict.go:57 +0xfd
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/keysbuilder.(*Builder).Update(0xc000118280, {0xc96d70, 0xc001e4d020}, {0xc8f5c0, 0xc00039c5d0})
autoupdate_1        |   /root/internal/keysbuilder/keysbuilder.go:125 +0x3c3
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/autoupdate.(*connection).updatedData(0xc00053a2a0, {0xc96d70, 0xc001e4c480})
autoupdate_1        |   /root/internal/autoupdate/connection.go:110 +0x1ca
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/autoupdate.(*connection).Next-fm.(*connection).Next.func1({0xc96d70, 0xc001e4c480})
autoupdate_1        |   /root/internal/autoupdate/connection.go:58 +0x6e
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.sendMessages({0xc96d70, 0xc001e4c480}, {0xc8f000, 0xc00053a1c0}, 0x10?, {0xc8f520?, 0xc000118280?}, {0xc93210?, 0xc00011e4e0?}, 0x1)
autoupdate_1        |   /root/internal/http/http.go:331 +0xe2
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.autoupdateHandler.func1({0xc950e0, 0xc00053a1c0}, 0xc0001dfc20)
autoupdate_1        |   /root/internal/http/http.go:181 +0x959
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0x7f3b6ae2fda8?, {0xc950e0?, 0xc00053a1c0?}, 0x120?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.connectionCountMiddleware.func2({0xc950e0, 0xc00053a1c0}, 0xc0001dfc20)
autoupdate_1        |   /root/internal/http/http.go:485 +0x105
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0xc0001de240?, {0xc950e0?, 0xc00053a1c0?}, 0xc0001de240?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.authMiddleware.func3({0xc950e0, 0xc00053a1c0}, 0xc0001de240)
autoupdate_1        |   /root/internal/http/http.go:373 +0xce
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0xc0001de240?, {0xc950e0?, 0xc00053a1c0?}, 0x0?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.validRequest.func4({0xc950e0?, 0xc00053a1c0?}, 0x6e65ed?)
autoupdate_1        |   /root/internal/http/http.go:467 +0x6f
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0xc000120410?, {0xc950e0?, 0xc00053a1c0?}, 0x10?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | net/http.(*ServeMux).ServeHTTP(0x411fa5?, {0xc950e0, 0xc00053a1c0}, 0xc0001de240)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2683 +0x1ad
autoupdate_1        | net/http.serverHandler.ServeHTTP({0xc929a0?}, {0xc950e0?, 0xc00053a1c0?}, 0x6?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:3137 +0x8e
autoupdate_1        | net/http.(*conn).serve(0xc00024db00, {0xc96d70, 0xc00011ec90})
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2039 +0x5e8
autoupdate_1        | created by net/http.(*Server).Serve in goroutine 1
autoupdate_1        |   /usr/local/go/src/net/http/server.go:3285 +0x4b4
autoupdate_1        | 2024/03/01 12:10:16 http: panic serving 172.22.0.14:42350: runtime error: invalid memory address or nil pointer dereference
autoupdate_1        | goroutine 2985 [running]:
autoupdate_1        | net/http.(*conn).serve.func1()
autoupdate_1        |   /usr/local/go/src/net/http/server.go:1898 +0xbe
autoupdate_1        | panic({0xabfe40?, 0x1146080?})
autoupdate_1        |   /usr/local/go/src/runtime/panic.go:770 +0x132
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/pkg/datastore/dsfetch.(*ValueInt).Lazy(...)
autoupdate_1        |   /root/pkg/datastore/dsfetch/fields_generated.go:195
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.Speaker.see.func1(0x2, {0xc00019ba00, 0xa, 0x10})
autoupdate_1        |   /root/internal/restrict/collection/speaker.go:73 +0x533
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.eachMeeting({0xc96d70, 0xc00011fbf0}, 0xc00039d380, {0xc95b00, 0x11c8e20}, {0xc0000df040, 0xa, 0xc00007e808?}, 0xc0000febc8)
autoupdate_1        |   /root/internal/restrict/collection/collection.go:260 +0x3cf
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.Speaker.see({}, {0xc96d70?, 0xc00011fbf0?}, 0xc0000fec28?, {0xc0000df040?, 0xa89220?, 0xc0000fec01?})
autoupdate_1        |   /root/internal/restrict/collection/speaker.go:43 +0x6b
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.(*restrictCache).Modes.func1({0xc96d70, 0xc00011fbf0}, 0xc00039d380, {0xc0000deff0, 0xa, 0x1?})
autoupdate_1        |   /root/internal/restrict/collection/collection.go:120 +0x2d3
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict.restrict({0xc96d70, 0xc00011fbf0}, {0xc8f360, 0xc00039cf78}, 0x2, 0xc0051006f0)
autoupdate_1        |   /root/internal/restrict/restrict.go:126 +0x791
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict.restricter.Get({{0xc8f360?, 0xc00039cf78?}, 0x40?}, {0xc96d70, 0xc00011fbf0}, {0xc0048a8620?, 0x1?, 0xc000116750?})
autoupdate_1        |   /root/internal/restrict/restrict.go:57 +0xfd
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/keysbuilder.(*Builder).Update(0xc0001185a0, {0xc96d70, 0xc00011fbf0}, {0xc8f5c0, 0xc00039cfd8})
autoupdate_1        |   /root/internal/keysbuilder/keysbuilder.go:125 +0x3c3
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/autoupdate.(*connection).updatedData(0xc00053a700, {0xc96d70, 0xc00011f290})
autoupdate_1        |   /root/internal/autoupdate/connection.go:110 +0x1ca
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/autoupdate.(*connection).Next-fm.(*connection).Next.func1({0xc96d70, 0xc00011f290})
autoupdate_1        |   /root/internal/autoupdate/connection.go:58 +0x6e
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.sendMessages({0xc96d70, 0xc00011f290}, {0xc8f000, 0xc00053a620}, 0x10?, {0xc8f520?, 0xc0001185a0?}, {0xc93210?, 0xc00011e4e0?}, 0x1)
autoupdate_1        |   /root/internal/http/http.go:331 +0xe2
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.autoupdateHandler.func1({0xc950e0, 0xc00053a620}, 0xc00058a900)
autoupdate_1        |   /root/internal/http/http.go:181 +0x959
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0x7f3b6aabf0e0?, {0xc950e0?, 0xc00053a620?}, 0x120?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.connectionCountMiddleware.func2({0xc950e0, 0xc00053a620}, 0xc00058a900)
autoupdate_1        |   /root/internal/http/http.go:485 +0x105
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0xc00058a240?, {0xc950e0?, 0xc00053a620?}, 0xc00058a240?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.authMiddleware.func3({0xc950e0, 0xc00053a620}, 0xc00058a240)
autoupdate_1        |   /root/internal/http/http.go:373 +0xce
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0x4113af?, {0xc950e0?, 0xc00053a620?}, 0x0?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.validRequest.func4({0xc950e0?, 0xc00053a620?}, 0x6e65ed?)
autoupdate_1        |   /root/internal/http/http.go:467 +0x6f
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0xc000120410?, {0xc950e0?, 0xc00053a620?}, 0x10?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | net/http.(*ServeMux).ServeHTTP(0x411fa5?, {0xc950e0, 0xc00053a620}, 0xc00058a240)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2683 +0x1ad
autoupdate_1        | net/http.serverHandler.ServeHTTP({0xc929a0?}, {0xc950e0?, 0xc00053a620?}, 0x6?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:3137 +0x8e
autoupdate_1        | net/http.(*conn).serve(0xc000aaa360, {0xc96d70, 0xc00011ec90})
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2039 +0x5e8
autoupdate_1        | created by net/http.(*Server).Serve in goroutine 1
autoupdate_1        |   /usr/local/go/src/net/http/server.go:3285 +0x4b4
autoupdate_1        | 2024/03/01 12:10:16 http: panic serving 172.22.0.14:42356: runtime error: invalid memory address or nil pointer dereference
autoupdate_1        | goroutine 2989 [running]:
autoupdate_1        | net/http.(*conn).serve.func1()
autoupdate_1        |   /usr/local/go/src/net/http/server.go:1898 +0xbe
autoupdate_1        | panic({0xabfe40?, 0x1146080?})
autoupdate_1        |   /usr/local/go/src/runtime/panic.go:770 +0x132
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/pkg/datastore/dsfetch.(*ValueInt).Lazy(...)
autoupdate_1        |   /root/pkg/datastore/dsfetch/fields_generated.go:195
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.Speaker.see.func1(0x2, {0xc000158100, 0xa, 0x10})
autoupdate_1        |   /root/internal/restrict/collection/speaker.go:73 +0x533
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.eachMeeting({0xc96d70, 0xc005101890}, 0xc00039db30, {0xc95b00, 0x11c8e20}, {0xc0000df860, 0xa, 0xc000180008?}, 0xc0000febc8)
autoupdate_1        |   /root/internal/restrict/collection/collection.go:260 +0x3cf
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.Speaker.see({}, {0xc96d70?, 0xc005101890?}, 0xc0000fec28?, {0xc0000df860?, 0xa89220?, 0xc0000fec01?})
autoupdate_1        |   /root/internal/restrict/collection/speaker.go:43 +0x6b
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict/collection.(*restrictCache).Modes.func1({0xc96d70, 0xc005101890}, 0xc00039db30, {0xc0000df810, 0xa, 0x1?})
autoupdate_1        |   /root/internal/restrict/collection/collection.go:120 +0x2d3
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict.restrict({0xc96d70, 0xc005101890}, {0xc8f360, 0xc00039d740}, 0x2, 0xc000406d50)
autoupdate_1        |   /root/internal/restrict/restrict.go:126 +0x791
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/restrict.restricter.Get({{0xc8f360?, 0xc00039d740?}, 0x40?}, {0xc96d70, 0xc005101890}, {0xc0046e44b0?, 0x1?, 0xc000117920?})
autoupdate_1        |   /root/internal/restrict/restrict.go:57 +0xfd
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/keysbuilder.(*Builder).Update(0xc000118840, {0xc96d70, 0xc005101890}, {0xc8f5c0, 0xc00039d788})
autoupdate_1        |   /root/internal/keysbuilder/keysbuilder.go:125 +0x3c3
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/autoupdate.(*connection).updatedData(0xc00053a8c0, {0xc96d70, 0xc005100f00})
autoupdate_1        |   /root/internal/autoupdate/connection.go:110 +0x1ca
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/autoupdate.(*connection).Next-fm.(*connection).Next.func1({0xc96d70, 0xc005100f00})
autoupdate_1        |   /root/internal/autoupdate/connection.go:58 +0x6e
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.sendMessages({0xc96d70, 0xc005100f00}, {0xc8f000, 0xc00053a7e0}, 0x10?, {0xc8f520?, 0xc000118840?}, {0xc93210?, 0xc00011e4e0?}, 0x1)
autoupdate_1        |   /root/internal/http/http.go:331 +0xe2
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.autoupdateHandler.func1({0xc950e0, 0xc00053a7e0}, 0xc000411c20)
autoupdate_1        |   /root/internal/http/http.go:181 +0x959
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0x7f3b6ab8fee8?, {0xc950e0?, 0xc00053a7e0?}, 0x120?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.connectionCountMiddleware.func2({0xc950e0, 0xc00053a7e0}, 0xc000411c20)
autoupdate_1        |   /root/internal/http/http.go:485 +0x105
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0xc0004117a0?, {0xc950e0?, 0xc00053a7e0?}, 0xc0004117a0?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.authMiddleware.func3({0xc950e0, 0xc00053a7e0}, 0xc0004117a0)
autoupdate_1        |   /root/internal/http/http.go:373 +0xce
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0xc0004117a0?, {0xc950e0?, 0xc00053a7e0?}, 0x0?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | github.com/OpenSlides/openslides-autoupdate-service/internal/http.HandleAutoupdate.validRequest.func4({0xc950e0?, 0xc00053a7e0?}, 0x6e65ed?)
autoupdate_1        |   /root/internal/http/http.go:467 +0x6f
autoupdate_1        | net/http.HandlerFunc.ServeHTTP(0xc000120410?, {0xc950e0?, 0xc00053a7e0?}, 0x10?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2166 +0x29
autoupdate_1        | net/http.(*ServeMux).ServeHTTP(0x411fa5?, {0xc950e0, 0xc00053a7e0}, 0xc0004117a0)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2683 +0x1ad
autoupdate_1        | net/http.serverHandler.ServeHTTP({0xc929a0?}, {0xc950e0?, 0xc00053a7e0?}, 0x6?)
autoupdate_1        |   /usr/local/go/src/net/http/server.go:3137 +0x8e
autoupdate_1        | net/http.(*conn).serve(0xc000249a70, {0xc96d70, 0xc00011ec90})
autoupdate_1        |   /usr/local/go/src/net/http/server.go:2039 +0x5e8
autoupdate_1        | created by net/http.(*Server).Serve in goroutine 1
autoupdate_1        |   /usr/local/go/src/net/http/server.go:3285 +0x4b4
```

**Comment by ostcar** [comment]
I can not reproduce this. Can you tell me more about your database? Is there a list of speaker? Who is on the list?

I looked at the code. I think the error could happen, if there is a `speaker` object, where the field `speaker.meeting_user_id` is set to 0. 

I can see in the models.yml, that this field is not required. So there is a bug in the autoupdate-service. The autoupdate-service has to handle the case of a speaker with `speaker.meeting_user_id` == 0.

But I don't understand the case. What does a speaker object with no meeting_user mean?

**Comment by ostcar** [comment]
I was able to reproduce this error. You have to speak with a user and then delete it. It login as Participant A with the permissions as described by @Elblinator.

With the PR https://github.com/OpenSlides/openslides-autoupdate-service/pull/872, it is fixed for me.

(But there is another bug, probably on the client. If there are 3 last speakers, and the the second speaker was deleted, then the client does not show the first speaker)

As Admin:
![as-admin](https://github.com/OpenSlides/openslides-autoupdate-service/assets/977937/32be2184-8646-4a94-9fd2-6313f86736c4)

As User, that is not allowed to see the LoS, but can be speaker
![as-user](https://github.com/OpenSlides/openslides-autoupdate-service/assets/977937/d71ce758-6730-4d56-9ce8-fc3ee0de1720)

**Comment by Elblinator** [comment]
The screenshot from the last speakers list from a User, that is not allowed to see the LoS, but can be speaker is correct 
Such a User can only see themselves on the LoS and on the Last speakers list
